export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const GET_PHOTOS = 'GET_PHOTOS'
export const GET_ONE_PHOTO = 'GET_ONE_PHOTO'
export const GET_BG = 'GET_BG'
export const LOGIN = 'LOGIN'
export const IS_LOGIN = 'IS_LOGIN'
export const LOGOUT = 'LOGOUT'
